Bug fix: Install library header for package 'jpeg'
rjcommon.h:11:10: fatal error: jpeglib.h: No such file or directory
 #include <jpeglib.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [/usr/local/lib/R/etc/Makeconf:168: read.o] Error 1
ERROR: compilation failed for package 'jpeg'

This issue fixes the bug introduced by the lack of the jpeglib.h header
required by the package 'jpeg' and all it's dependencies.

The same issue is present in both release and devel branches of the base
images, i.e, release_base2 and devel_base2. It results from
rocker/rstudio:3.6.2 images where this header seems to be not available.